services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php

  php:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    links:
      - db

  db:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: docker/db/Dockerfile
      args:
        POSTGRES_DB: ${POSTGRES_DB}   # Pass POSTGRES_DB as build argument
    ports:
      - "${PGPORT}:${PGPORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      PGPORT: ${PGPORT}

  pgadmin:
    env_file:
      - ./.env
    image: dpage/pgadmin4:latest
    container_name: pg-admin2
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
